# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    driver: "gd"
    resolvers:
        default:
            web_path: ~
    twig:
        mode: lazy
    filter_sets:
        cache: ~
        thumbnail_frontend:
            quality: 75
            filters:
                thumbnail: { size: [90, 60], mode: outbound }
        thumbnail_admin:
            quality: 75
            filters:
                thumbnail: { size: [45, 30], mode: outbound }
        preview:
            quality: 75
            filters:
                thumbnail: { size: [300], mode: outbound }
